In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
df = pd.read_csv('/Users/mahaswetasarkar/Downloads/customer.csv')

In [36]:
df.sample(5)

,age,gender,review,education,purchased
1,68,Female,Poor,UG,No
27,69,Female,Poor,PG,No
26,53,Female,Poor,PG,No
43,27,Male,Poor,PG,No
21,32,Male,Average,PG,No


In [37]:
# Age(x1) - Discreat 
# gender(x2) - Nominal -- One_hot_encording
# review(x3) - ordinal -- Ordinal_encording
# education(x4) - ordinal -- Ordinal_encording
# purchased(y)-Nominal -- One_hot_encording
#we will work on ordinal encoding now 

In [38]:
df = df.iloc[:,2:]

In [39]:
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [41]:
X = df.iloc[:,:2]

In [43]:
#X

In [44]:
y = df.iloc[:,-1]

# Train_test_split

In [45]:
from sklearn.model_selection import train_test_split 

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Ordinal Encording:

In [48]:
from sklearn.preprocessing import OrdinalEncoder

In [51]:
X_train['review'].value_counts()

review
Good       16
Poor       13
Average    11
Name: count, dtype: int64

In [53]:
X_train['review'].nunique()

3

In [54]:
X_train['review'].unique()

array(['Poor', 'Average', 'Good'], dtype=object)

In [55]:
X_train['education'].value_counts()

education
School    14
PG        14
UG        12
Name: count, dtype: int64

In [56]:
X_train['education'].nunique()

3

In [57]:
X_train['education'].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [58]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'],['School', 'UG', 'PG']])

In [59]:
oe.fit_transform(X_train)

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [60]:
oe.transform(X_test)

array([[1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.]])

# Label Encording

In [61]:
from sklearn.preprocessing import LabelEncoder

In [62]:
le = LabelEncoder()

In [63]:
le.fit_transform(y_train)

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [64]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [65]:
le.transform(y_test)

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1])

In [ ]:
Although purchased(y) is Nominal data for that we should apply One_hot_encording but here I have just tried labe